---

# Create Instances
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item.0.name }}"
    state: "{{ item.0.state }}"
    image: "{{ item.0.image }}"
    key_name: "{{ item.0.key_name }}"
    flavor: "{{ item.0.flavor }}"
    security_groups: "{{ item.0.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "{{ item.1 }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  with_subelements: 
    - "{{ osp_servers }}"
    - meta

- name: Add floating IP to instance
  os_floating_ip:
    cloud: openstack
    state: "{{ item.value.state }}"
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  with_dict: "{{ osp_servers}}"


# Send pub key to each instances
- name: OpenStack servers
  os_server_info:
    cloud: openstack
  register: result

- name: Set authorized key taken from file
  authorized_key:
    user: cloud-user
    state: present
    key: "http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub"
  with_items: "{{ result.openstack_servers }}"
