---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: remove internal repos
  file:
    path: /etc/yum.repos.d/internal.repo
    state: absent

#- name: setup hostname
#  hostname:
#    name: "{{ inventory_hostname }}"
 
- name: install base tools and packages
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - httpie
    - python-pip

